spring:
  application:
    name: service-consumer-movie
server:
  port: 7901
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka
  instance:
    ip-address: true
